### ISSUE TITLE
Remove autocomplete

### ISSUE THREAD

**Issue by vianettom** [mivicker/fastbot#1]
**Describe the bug**
My brother in christ, the sentence autocomplete is annoying

**Expected behavior**
he should just chill

**To Reproduce**

**Screenshots**
If applicable, add screenshots / animated gifs / loom video links to help explain your problem.

**Known user types the reported issue is affecting**
- [x] User
- [ ] Admin
- [ ] Other

**Account the issue is affecting**

**URL where bug can be viewed (if applicable)**

**Severity of bug:**
- [ ] Critical: this issue affects critical functionality or data. It does not have a workaround. Example: complete failure of a feature
- [ ] Major: this issue affects major functionality or major data. It has a workaround but is not obvious and is difficult. Example: A feature is not functional but the task at hand can be accomplished with complicated or tedious workarounds
- [x] Minor: this issue affects minor functionality or non-critical data. It has an easy workaround. Example: A minor feature is not functioning as expected, but does not prevent someone from doing their job 
- [ ] Trivial: this issue does not affect functionality or data. It does not even need a workaround. Example: Layout discrepancies, text changes

**Priority of bug:**
- [ ] High: Must be fixed immediately.
- [x] Medium: Must be fixed in the current or next release.
- [ ] Low: May be fixed next release.
- [ ] Await Prioritization: Can be fixed when priority allows.

**Additional context**

**Comment by mivicker** [comment]
I made the api call configuration options available to the chat. Adjusting those should allow users to find the combo that avoids repeats. Likely has something to do with the "temperature" setting.
